services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile
    image: debian:42
    container_name: debian42
    network_mode: host # Use host network
    volumes:
      - x11:/tmp/.X11-unix:ro             # Share X11 socket. Make sure to `xhost +local:docker` on host
      - ping_output:/home/ping_output:ro
    environment:
      - DISPLAY=${DISPLAY} # Set DISPLAY environment variable
    cap_add: # Add capabilities (Wireshark)
      - NET_ADMIN
      - NET_RAW

volumes:
  x11:
    driver: local
    driver_opts:
      type: none
      device: /tmp/.X11-unix
      o: bind
  ping_output:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/ping_output
      o: bind